<Sensors>:
    Label:
        id: label1_acc
        pos: 150, 300
        text: 'acc_x: '

    Label:
        id: label2_acc
        pos: 150, 250
        text: 'acc_y: '

    Label:
        id: label3_acc
        pos: 150, 200
        text: 'acc_z: '

    Label:
        id: status
        pos: 150, 150
        text: ''

    Button:
        id: button1
        pos: 150, 50
        text: 'Start'
        on_press: root.pressed1()